Load passport
cusodede/dpl pull request #109
Opened 2021-07-26 13:48 UTC by pepebotika69

2021-07-27 20:09 UTC, pozitronik requested changes

2021-07-27 20:09 UTC, pozitronik commented on modules/dol/models/DolAPIInterface.php
> +	public function registerCreate(string $verificationToken, Sellers $seller):DefaultResponse;
Если в интерфейсе объявляется метод, то он должен быть реализован в имплементирующих классах (речь о MemoryDolAPi)

2021-07-27 20:09 UTC, pozitronik commented on modules/dol/models/DolAPIInterface.php
> +	public function confirmSmsLogon(string $phoneAsLoginRaw, string $code):ConfirmSmsResponse;
Названия параметров желательно сохранять идентичными и в объявлении и в имплементации метода.

2021-07-28 10:13 UTC, pepebotika69 commented on modules/dol/models/DolAPIInterface.php
> +	public function registerCreate(string $verificationToken, Sellers $seller):DefaultResponse;
+

2021-07-28 10:13 UTC, pepebotika69 commented on modules/dol/models/DolAPIInterface.php
> +	public function confirmSmsLogon(string $phoneAsLoginRaw, string $code):ConfirmSmsResponse;
+

2021-07-28 13:14 UTC, pozitronik approved these changes

2021-07-28 13:15 UTC, pozitronik approved these changes

2021-07-28 13:15 UTC, merged