Issue 13
cusodede/dpl pull request #17
Opened 2021-05-17 13:31 UTC by pepebotika69

Все что заметил и придумал сделал. думаю для мвп это достаточно.

2021-05-17 20:38 UTC, pozitronik commented on .idea/inspectionProfiles/Quick.xml
> -    <inspection_tool class="AngularAmbiguousComponentTag" enabled="true" level="ERROR" enabled_by_default="true" />
Видимо, ты поменял одну опцию, но в конфиг ушли все твои локальные.
Не, не годится. Убери это изменение из патча, а проверку переносов я отключу в конфиге апстрима.

2021-05-17 20:40 UTC, pozitronik requested changes
Патч ОК, но пущу после фикса конфига, просто чтоб случаем не прошло дальше.

2021-05-18 06:54 UTC, pepebotika69 commented on .idea/inspectionProfiles/Quick.xml
> -    <inspection_tool class="AngularAmbiguousComponentTag" enabled="true" level="ERROR" enabled_by_default="true" />
@pozitronik поправил

2021-05-18 06:54 UTC, pozitronik approved these changes

2021-05-18 07:05 UTC, merged