Issue 206
cusodede/dpl pull request #228
Opened 2021-09-01 10:40 UTC by s1lver

Модуль СНМП для работы с очередью событий регистрации договоров в ДОЛ.
## Запуск
```
php8 yii mq-dol-contract-register/listen
```
Дальше или Supervisor будет следить или через .service поднимать. Потом обсудим как лучше. Я, сейчас, склоняюсь к supervisor.

## Логика

- Ожидаем push RabbitMQ
- Получаем сообщение
- Десериализуем сообщение
- Кидаем событие **EVENT_CONTRACT_REGISTER** для DPL
- Где-то слушаем событие **EVENT_CONTRACT_REGISTER** и выполняем нужные действия

## Структура

Поскольку ожидается что будем работать с очередями внутри DPL, то конфиг должен соответствовать соглашению. Например, mqDolContractRegister разбивается на:
- mq - обязательный префикс 
- Dol - поставщик
- ContractRegister - событие

## Docker
Отдельной задачкой добавим, с полпинка не завелось(

2021-09-01 17:08 UTC, s1lver commented
Надо еще добавить получение traceparent

2021-09-02 06:55 UTC, pepebotika69 commented on modules/nsis/NsisModule.php
> +		} catch (Exception $e) {
Undefined class 'Exception'

2021-09-02 07:19 UTC, s1lver commented on modules/nsis/NsisModule.php
> +		} catch (Exception $e) {
Исправлено. В IntelliJ проставился по умолчанию профиль Grammar(

2021-09-02 07:56 UTC, pepebotika69 commented on modules/nsis/models/job/TestJob.php
> +namespace app\modules\nsis\models\nsis\job;
app\modules\nsis\models\nsis\job два раза nsis ok? 
Смотри:  @package app\modules\nsis\models\job

2021-09-02 07:56 UTC, pepebotika69 commented on tests/unit/modules/rabbit_mq/models/nsis/DolNsisSerializerTest.php
> +		'ban' => '123',
откуда бан? в конфлуенсе нет такого

2021-09-02 07:58 UTC, s1lver commented on tests/unit/modules/rabbit_mq/models/nsis/DolNsisSerializerTest.php
> +		'ban' => '123',
BAN договора, договорились что Леша будет нам его присылать. Описание дополнил

2021-09-02 10:49 UTC, s1lver commented on modules/nsis/models/job/TestJob.php
> +namespace app\modules\nsis\models\nsis\job;
Готово

2021-09-02 10:49 UTC, s1lver commented on tests/unit/modules/rabbit_mq/models/nsis/DolNsisSerializerTest.php
> +		'ban' => '123',
Добавлено

2021-09-03 08:52 UTC, pozitronik requested changes

2021-09-03 08:52 UTC, pozitronik commented on composer.json
> +		"kartik-v/yii2-password": "dev-master",
При изменении набора компонентов делаем composer update и обновляем composer.lock в индексе.

2021-09-03 08:52 UTC, pozitronik commented on modules/nsis/models/job/DolContractRegisterJob.php
> +	public int $contractId;
Рекомендую выносить описания публичных свойств в @property-блоки. Это именно рекомендация - так оно как-то привычнее выглядит и ощущается, но никаких особых практических последствий не имеет.

2021-09-03 08:52 UTC, pozitronik commented on modules/nsis/commands/TestController.php
> +		$rabbitMQ = Yii::$app->mqDolContractRegister;
У нас есть файлик `support/ide-helper.php`, используй его для глобального описания подобных подключений.

2021-09-03 12:37 UTC, s1lver commented on composer.json
> +		"kartik-v/yii2-password": "dev-master",
Готово

2021-09-03 12:37 UTC, s1lver commented on modules/nsis/commands/TestController.php
> +		$rabbitMQ = Yii::$app->mqDolContractRegister;
Готово

2021-09-03 14:09 UTC, pepebotika69 approved these changes

2021-09-05 14:50 UTC, pozitronik requested changes
Кодстайл не проектный.
Коммиты не атомарные.

2021-09-05 14:50 UTC, pozitronik commented on modules/nsis/models/job/DolContractRegisterJob.php
> +class DolContractRegisterJob extends BaseObject implements JobInterface
Форматирование непроектное.

2021-09-06 06:57 UTC, s1lver commented on modules/nsis/models/job/DolContractRegisterJob.php
> +class DolContractRegisterJob extends BaseObject implements JobInterface
Ctr+Al+L готово

2021-09-06 07:06 UTC, pozitronik approved these changes

2021-09-07 06:14 UTC, artemvolt commented on modules/nsis/NsisModule.php
> +			Yii::error($e->getTraceAsString());
Можно просто передавать Yii::error($e) тогда у тебя в логе будет ошибка со всеми данными.

2021-09-07 06:17 UTC, artemvolt commented on modules/nsis/commands/TestController.php
> +	public function actionSendMessage(string $message):void {
Добавь в support/ide_helper.php свойство mqDolContractRegister и укажи класс, чтобы подсветка и автодополнение работали :)

2021-09-07 06:18 UTC, artemvolt approved these changes

2021-09-07 06:19 UTC, artemvolt commented
Конфликт с мастером

2021-09-07 07:01 UTC, s1lver commented
Решил конфликт с composer.lock

2021-09-07 07:34 UTC, merged