dspl #76 Реализовать синхронизацию тарифов менжду DOL|DPL
cusodede/dpl pull request #231
Opened 2021-09-01 12:00 UTC by pepebotika69

2021-09-03 08:24 UTC, pozitronik requested changes

2021-09-03 08:24 UTC, pozitronik commented on migrations/m210826_093522_RefTariffs.php
> +use yii\db\Migration;
Используем \app\components\db\Migration;

2021-09-03 08:24 UTC, pozitronik commented on migrations/m210830_084047_edit_rewards_rules.php
> +use yii\db\Migration;
Используем \app\components\db\Migration;

2021-09-03 08:24 UTC, pozitronik commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
Статику пишем в CamelCase, зачем переименовал?

2021-09-03 08:24 UTC, pozitronik commented on models/rewards_rules/RewardsRules.php
> +		$socId += ArrayHelper::getColumn(
Разве логика запросов не меняется?

2021-09-06 07:10 UTC, pepebotika69 commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
потому что когда я raedme читал не видел такое правило, да и не нужен мне кажется, усложняет сам процесс написания кода

2021-09-06 07:14 UTC, s1lver commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
Согласен с Ваней. Не понятно что это дает? Понятие что это статика? Так и так видно же, зачем усложнять

2021-09-06 08:21 UTC, pozitronik commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
У нас 

> 
> 
> потому что когда я raedme читал не видел такое правило, да и не нужен мне кажется, усложняет сам процесс написания кода

У нас действительно нет такого правила. И статические вызовы у нас именуются вразнобой. И линтер у нас не предъявляет жёстких требований к именованиям литералов. Это плохо, и это та вещь, о которой я не успел позаботиться.
Поэтому в каждом конкретном случае приходится ориентироваться по текущим соображениям. Например тут `getTariffRule(...)` может триггернуть _тупую_ проверку плагина yii inspections про наличие геттера (имя функции условно попадает под регэксп `^get*`) без объявленного атрибута. Поэтому называем метод `GetTariffRule()` и живём спокойно.

2021-09-06 08:23 UTC, s1lver commented on models/rewards_rules/RewardsRules.php
> +		);
Может стоит получить все варианты soc одним запросом?

2021-09-06 08:26 UTC, s1lver commented on models/rewards_rules/RewardsRules.php
> +		$searchQuery->orFilterWhere([self::tableName().'.soc' => $socId]);
И вот тут тоже момент. Сложно сказать сколько тут идентификаторов будет в IN. Это планируется используется только в панели управления?

2021-09-06 09:00 UTC, pepebotika69 commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
@pozitronik 
тут базара нет, я поменяю и оставлю как было. Зря полез поправлять. Но в целом думаешь это настолько важно чтобы ломать и так уже покалеченную психику португальца? может забить на это?

2021-09-06 09:11 UTC, pozitronik commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
> 
> 
> @pozitronik
> тут базара нет, я поменяю и оставлю как было. Зря полез поправлять. Но в целом думаешь это настолько важно чтобы ломать и так уже покалеченную психику португальца? может забить на это?

Бразилец первый начал!

2021-09-06 09:29 UTC, pepebotika69 commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
понял.

2021-09-06 09:43 UTC, pepebotika69 commented on migrations/m210826_093522_RefTariffs.php
> +use yii\db\Migration;
готово

2021-09-06 09:43 UTC, pepebotika69 commented on migrations/m210830_084047_edit_rewards_rules.php
> +use yii\db\Migration;
готово

2021-09-06 09:45 UTC, pepebotika69 commented on models/rewards/Rewards.php
> +	public static function getTariffRule(int $tariff, ?int $user = null):?RewardsRules {
готово

2021-09-06 10:25 UTC, s1lver commented on models/rewards_rules/RewardsRules.php
> +		$searchQuery->orFilterWhere([self::tableName().'.soc' => $socId]);
Вопрос снят

2021-09-06 10:26 UTC, s1lver commented on models/rewards_rules/RewardsRules.php
> +		);
Этот тоже. Только фиксик ждем

2021-09-06 11:16 UTC, pepebotika69 commented on models/rewards_rules/RewardsRules.php
> +		$socId += ArrayHelper::getColumn(
да, поправил.

2021-09-06 11:36 UTC, pepebotika69 commented on models/rewards_rules/RewardsRules.php
> +		);
готово

2021-09-06 13:03 UTC, s1lver approved these changes

2021-09-06 13:03 UTC, s1lver commented on models/tariffs/RefTariffs.php
> +	public function getView_columns():array {
У нас есть соглашение о подписи переопределяемых методов? Или пофиг?

2021-09-06 17:04 UTC, pozitronik commented on models/tariffs/RefTariffs.php
> +	public function getView_columns():array {
Нет, не пофиг. Должен быть @inheritdoc, а если сигнатура отличается - то дока по изменениям.

2021-09-06 17:28 UTC, pozitronik approved these changes

2021-09-06 17:29 UTC, merged