Сохранение полученной информации о регистрации договора
cusodede/dpl pull request #240
Opened 2021-09-03 12:46 UTC by s1lver

Пока в драфте

2021-09-03 14:02 UTC, pepebotika69 approved these changes

2021-09-05 14:47 UTC, pozitronik requested changes
Соблюдай атомарность коммитов. Один коммит - одно логическое изменение. Здесь хотелось бы разделения на
- crud (можно вместе с миграцией)
- конфиги
- компоненты
- тесты.

Конкретно здесь можно не переделывать, но на будущее учитывай.

Из хотелок: сейчас контракты могут пополниться только извне. Наш DefaultController и его обвязка построены так, чтобы добавлять редактор к любым AR, даже если это не требуется на бою - но тесты и эксперименты-то никто не отменял. Добавь.

2021-09-05 14:47 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +class m210902_112037_create_contracts_table extends Migration
Миграции наследуем от `app\components\db\Migration`

2021-09-05 14:47 UTC, pozitronik commented on controllers/ContractsController.php
> +class ContractsController extends DefaultController
Везде должно быть проектное форматирование кода.

2021-09-05 14:47 UTC, pozitronik commented on views/contracts/index.php
> +			'heading' => $this->title.(($dataProvider->totalCount > 0)?
Как-то прям странно отформатировал тернарник. Мы придерживаемся вида
```php
condition()
	?positive-result
	:negative-result

```

2021-09-05 14:47 UTC, pozitronik commented on tests/_bootstrap.php
> +ob_start();
Можешь пояснить необходимость?

2021-09-06 06:29 UTC, s1lver commented on tests/_bootstrap.php
> +ob_start();
Для возможности запускать тесты из IDE.

2021-09-06 06:34 UTC, s1lver commented
> Соблюдай атомарность коммитов. Один коммит - одно логическое изменение. Здесь хотелось бы разделения на
> 
>     * crud (можно вместе с миграцией)
> 
>     * конфиги
> 
>     * компоненты
> 
>     * тесты.
> 
> 
> Конкретно здесь можно не переделывать, но на будущее учитывай.
> 
> Из хотелок: сейчас контракты могут пополниться только извне. Наш DefaultController и его обвязка построены так, чтобы добавлять редактор к любым AR, даже если это не требуется на бою - но тесты и эксперименты-то никто не отменял. Добавь.

Какие конфиги? Тут нет конфигов. Соответственно, я ветку сделал от 206, так как без нее не имело смысла делать эту задачу. Осюда и конфиги из прошлой задачи.
И что тут конкретно тестировать? Реализация проще не куда.

2021-09-06 06:49 UTC, pozitronik commented
> 
> 
> > Соблюдай атомарность коммитов. Один коммит - одно логическое изменение. Здесь хотелось бы разделения на
> > ```
> > * crud (можно вместе с миграцией)
> > 
> > * конфиги
> > 
> > * компоненты
> > 
> > * тесты.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Конкретно здесь можно не переделывать, но на будущее учитывай.
> > Из хотелок: сейчас контракты могут пополниться только извне. Наш DefaultController и его обвязка построены так, чтобы добавлять редактор к любым AR, даже если это не требуется на бою - но тесты и эксперименты-то никто не отменял. Добавь.
> 
> Какие конфиги? Тут нет конфигов. Соответственно, я ветку сделал от 206, так как без нее не имело смысла делать эту задачу. Осюда и конфиги из прошлой задачи.
> И что тут конкретно тестировать? Реализация проще не куда.

Женя, речь об разбиении коммитов. Ты в одном [коммите](https://github.com/cusodede/dpl/commit/c10d4c4225a6aacf28c0970811131c5abf00667d) cделал изменения по миграции, моделям, контроллерам, вьюхам, конфигам, компонентам и тестам. Это нарушает принцип атомарности изменений.
Проговорим с тобой отдельно.

2021-09-06 07:00 UTC, s1lver commented
> > > Соблюдай атомарность коммитов. Один коммит - одно логическое изменение. Здесь хотелось бы разделения на
> > > ```
> > > * crud (можно вместе с миграцией)
> > > 
> > > * конфиги
> > > 
> > > * компоненты
> > > 
> > > * тесты.
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Конкретно здесь можно не переделывать, но на будущее учитывай.
> > > Из хотелок: сейчас контракты могут пополниться только извне. Наш DefaultController и его обвязка построены так, чтобы добавлять редактор к любым AR, даже если это не требуется на бою - но тесты и эксперименты-то никто не отменял. Добавь.
> > 
> > 
> > Какие конфиги? Тут нет конфигов. Соответственно, я ветку сделал от 206, так как без нее не имело смысла делать эту задачу. Осюда и конфиги из прошлой задачи.
> > И что тут конкретно тестировать? Реализация проще не куда.
> 
> Женя, речь об разбиении коммитов. Ты в одном [коммите](https://github.com/cusodede/dpl/commit/c10d4c4225a6aacf28c0970811131c5abf00667d) cделал изменения по миграции, моделям, контроллерам, вьюхам, конфигам, компонентам и тестам. Это нарушает принцип атомарности изменений.
> Проговорим с тобой отдельно.

Потому что вся задача была в один коммит.

2021-09-06 07:11 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +class m210902_112037_create_contracts_table extends Migration
Готово

2021-09-06 12:14 UTC, pozitronik requested changes
Миграция падает на pgsql
```
*** applying m210902_112037_create_contracts_table
    > create table {{%contracts}} ... done (time: 0.061s)
    > create index {{%contracts}}_CONTRACT_CONTRACT_ID on {{%contracts}} (contractId) ...Exception: SQLSTATE[42601]: Syntax error: 7 ОШИБКА:  ошибка синтаксиса (примерное положение: "_CONTRACT_CONTRACT_ID")
LINE 1: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts"...
                                ^
The SQL being executed was: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts" ("contractId") (D:\LIFE\OpenServer\domains\dpl\vendor\yiisoft\yii2\db\Schema.php:678)
```

2021-09-06 12:48 UTC, s1lver commented
> Миграция падает на pgsql
> 
> ```
> *** applying m210902_112037_create_contracts_table
>     > create table {{%contracts}} ... done (time: 0.061s)
>     > create index {{%contracts}}_CONTRACT_CONTRACT_ID on {{%contracts}} (contractId) ...Exception: SQLSTATE[42601]: Syntax error: 7 ОШИБКА:  ошибка синтаксиса (примерное положение: "_CONTRACT_CONTRACT_ID")
> LINE 1: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts"...
>                                 ^
> The SQL being executed was: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts" ("contractId") (D:\LIFE\OpenServer\domains\dpl\vendor\yiisoft\yii2\db\Schema.php:678)
> ```

Падает только с компонентом этим. Если использовать стандартный yii\db\Migration, то все нормально проходит.

2021-09-06 13:30 UTC, pozitronik commented
> 
> 
> > Миграция падает на pgsql
> > ```
> > *** applying m210902_112037_create_contracts_table
> >     > create table {{%contracts}} ... done (time: 0.061s)
> >     > create index {{%contracts}}_CONTRACT_CONTRACT_ID on {{%contracts}} (contractId) ...Exception: SQLSTATE[42601]: Syntax error: 7 ОШИБКА:  ошибка синтаксиса (примерное положение: "_CONTRACT_CONTRACT_ID")
> > LINE 1: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts"...
> >                                 ^
> > The SQL being executed was: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts" ("contractId") (D:\LIFE\OpenServer\domains\dpl\vendor\yiisoft\yii2\db\Schema.php:678)
> > ```
> 
> Падает только с компонентом этим. Если использовать стандартный yii\db\Migration, то все нормально проходит.

Не говори мне то, что я и так знаю =)
Решения, предложения, исправления?

2021-09-06 13:39 UTC, s1lver commented
> > > Миграция падает на pgsql
> > > ```
> > > *** applying m210902_112037_create_contracts_table
> > >     > create table {{%contracts}} ... done (time: 0.061s)
> > >     > create index {{%contracts}}_CONTRACT_CONTRACT_ID on {{%contracts}} (contractId) ...Exception: SQLSTATE[42601]: Syntax error: 7 ОШИБКА:  ошибка синтаксиса (примерное положение: "_CONTRACT_CONTRACT_ID")
> > > LINE 1: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts"...
> > >                                 ^
> > > The SQL being executed was: CREATE INDEX "contracts"_CONTRACT_CONTRACT_ID ON "contracts" ("contractId") (D:\LIFE\OpenServer\domains\dpl\vendor\yiisoft\yii2\db\Schema.php:678)
> > > ```
> > 
> > 
> > Падает только с компонентом этим. Если использовать стандартный yii\db\Migration, то все нормально проходит.
> 
> Не говори мне то, что я и так знаю =)
> Решения, предложения, исправления?

Видимо, решение не использовать компонент не подходит?)

2021-09-06 13:54 UTC, pozitronik commented
> 
> Видимо, решение не использовать компонент не подходит?)

Через этот компонент мы пытаемся обеспечить совместимость меж mysql/pgsql.
Возможно, мы что-то делаем неправильно. Мы этого не знаем.

У тебя есть два варианта. Первый - сказать "это не моя проблема", и отдать на разбор мне.
Второй - самому разобраться, что не так, получить новое знание, и уже с этим знанием решить, можешь ли ты сам внести исправления, или это должен делать кто-то другой.

2021-09-06 17:10 UTC, s1lver commented
По моему мнению, не надо всегда писать миграции наследуясь от этого компонента. Мы создали себе проблему и теперь пытаемся ее решить. Зачем обеспечивать совместимость там где это не требуется?
Для не стандартных вещей, я согласен, можно использовать, но только для тех вещей для которых не работает "из коробки". 

Пишется миграция. Запускается. Получаем ошибки. Исправляем ошибки. Профит. 
Если нам надо обеспечить для индексов "уникальные" имена, то проще принять соглашение о наименовании. Например:  сначала пишем ИМЯ ТАБЛИЦЫ _ ИМЯ КОЛОНКИ. При этом метод не будет за меня решать как назвать индекс, и не будет его резать при достижении пороговой длины.

Дело не в "это не моя проблема", а целесообразности использования того или другого. В данном случае, использование наследования от компонента `app\components\db\Migration`не нужно.

2021-09-06 17:39 UTC, s1lver commented
А по существу... то мы вмешались в обработку схемы фреймворка. В процессе квотирования {{%contracts}} превращается в "contracts". Соответственно, мы получаем на выходе вот такое имя индекса "contracts"_CONTRACT_CONTRACT_ID  что является нарушением синтаксиса. Поэтому падает запрос

 ```sql 
CREATE INDEX {{%contracts}}_CONTRACT_CONTRACT_ID ON {{%contracts}} (contractId)
```

2021-09-06 17:43 UTC, s1lver commented
Могу предложить вот такой костыль

```php
public function checkIndexName(string $name, string $table):string {
		if (0 !== substr_compare($name, $table, 0, strlen($table))) {//имя индекса не содержит имени таблицы
			$name = "{$table}_{$name}";
		}

		if (strlen($name) > 64 /*max index name length*/) {
			$name = substr($name, -64, 64);
		}
		return str_replace('"', '', $this->db->quoteSql($name));
	}
```

2021-09-06 20:19 UTC, pozitronik commented
Я уже и забыл, какое это удовольствие с тобой спорить =)

Вот тебе контекст.
`app\components\db\Migration` должен работать этакой наивной прослойкой совместимости, убирая с прикладного уровня разницу между миграциями в mysql и pgsql. Решения могут быть довольно костыльными - мы только учимся работать с pgsql, и за неимением лучшего варианта имеем, что имеем.
Тем не менее, эти решения взяты не с потолка. Мы с @htrv [потратили время на разбирательства](https://github.com/cusodede/bc/wiki/%D0%9C%D0%B8%D0%B3%D1%80%D0%B0%D1%86%D0%B8%D1%8F-MySQL=-PostgreSQL), и выяснили, например, что в pgsql имя индекса должно быть уникально в пределах неймспейса (а не в пределах БД, как в mysql).
Как убедиться, что имя индекса всегда будет уникально? Решений можно выдумать кучу, но самое простое, что приходит в голову, — добавлять к имени индекса название таблицы. Но мы не можем ретроспективно изменять старые миграции, это нарушает саму идею. Даже если мы на эту идею плюнем, то всё равно — ручная работа, а мы слишком ленивы для такого.
Поэтому просто переопределяем `createIndex()`, и проходимся автозаменой.
Но в некоторых миграциях подстановка имени таблицы в имя индекса уже делается. Соответственно, надо учесть, что если имя индекса начинается с имени таблицы, то ничего добавлять не нужно. Ок.
Дальше выясняем, что на mysql некоторые из имён идексов, полученные в результате такой автогенерации, могут превысить максимальную длину имени индекса в 64 символа. Учитывая, что нам абсолютно не важно, как называется индекс, просто "режем хвосты".
Наивное решение в лоб, как раз то, что тут нужно.

Теперь ты знаешь контекст, и мы можем разобрать твои аргументы.

>Зачем обеспечивать совместимость там где это не требуется?

Оказывается, требуется — во избежание коллизий в именах индексов.
Но даже если бы не требовалось — что-то может всплыть в будущем. И если все миграции будут наследоваться от прослойки совместимости, то фиксы можно будет внести в неё.

>Если нам надо обеспечить для индексов "уникальные" имена, то проще принять соглашение о наименовании.

Мы не можем применить такое соглашение "задним числом". Но можем сделать так, как сделали.

>Например: сначала пишем ИМЯ ТАБЛИЦЫ _ ИМЯ КОЛОНКИ.

Ты принял такое соглашение сам для себя, либо не поинтересовавшись, как принято писать у нас, либо проигнорировав это. В результате, так скажем, наткнулся на неучтённый момент. Если посмотришь существующие миграции — они могут быть написаны достаточно по разному в плане кода, но согласованно в плане именований. Не было необходимости как-то фиксировать этот момент документально, все следовали предложенному образцу изначально.
Но найденная ошибка (даже две: в перекрытом `createIndex()` не проверялись регистр имени индекса и формат имени таблицы) — это не твоя проблема. Однако, столкнувшись с ней, ты не стал выяснять контекст и причину, а объявил имеющееся решение не нужным.
Не стесняйся задавать вопросы, за них не наказывают. Более того, на твоей позиции ты **обязан** интересоваться всем, что связано с проектом.

>А по существу... то мы вмешались в обработку схемы фреймворка.

Да. Вполне осознанно. И теперь, наткнувшись на проблемы, так же осознанно, прямо и наивно их обойдём.

>Могу предложить вот такой костыль

Я кое-что с утра доработаю в нём, но в целом — мыслишь верно.

>Но, как я писал выше, мне не нравится что будет что-то дописываться без моего ведома.

Теперь ты уведомлен, нет причины для недовольства ;)

2021-09-06 20:31 UTC, pozitronik requested changes
поправить описанное и норм.
`app\components\db\Migration` поправлю я отдельным тикетом.

2021-09-06 20:31 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'status' => $this->json(),
Из разряда "мало ли, а вдруг?": нужно проверить, как `pgsql` работает с json-полями. Мы уже столкнулись с тем, что binary-поля отдаются как stream, и требуют других обработчиков. json же у нас в БД ещё не использовался.

2021-09-06 20:31 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
В общем-то, не особо имеет смысл — мы не используем $tablePrefix в предыдущих миграциях, и добавление его в одну миграцию просто ничего не даст. Но и не навредит, конечно.

2021-09-06 20:31 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createIndex('CONTRACT_CONTRACT_ID', '{{%contracts}}', 'contractId');
Имена индексов я всё-таки попрошу писать в нижнем регистре, чисто для сохранения единства стиля.

2021-09-06 20:31 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Для названий полей у нас snake_case.

2021-09-06 20:31 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'id' => $this->primaryKey()->unique(),
primaryKey() имеет уникальность сам по себе.

2021-09-07 07:07 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Это сделано намеренно чтобы дальше не городить мапинга а использовать средства фреймворка

2021-09-07 07:13 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
Это генерирует YII2. Можно убирать если нам не надо

2021-09-07 07:16 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'status' => $this->json(),
В Postgresql эти поля будут jsonb. А мы, пока, вообще не знаем что делать с этим полем и практического применения для себя не нашли. Поэтому status оставляем как есть. connections - посмотрим что с ним делать как только Артем до этого дойдет. Пока эти поля выглядят так.

2021-09-07 07:19 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'status' => $this->json(),
В коде получение данных из этих полей будет как выглядеть? Это будет строка, это будет ресурс, это будет массив, раскукоженный фреймворком?

2021-09-07 07:23 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
> 
> 
> Это генерирует YII2. Можно убирать если нам не надо

Генерирует откуда?
Наш шаблон миграции тут: `migrations/template/default_migration_template.php`, вроде бы он должен подсасываться на `migrate/create`.

2021-09-07 07:23 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Нужно snake_case.

2021-09-07 07:35 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
php yii migrate/create create_ИМЯТФБЛИЦЫ_table

2021-09-07 07:35 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
В общем я убрал

2021-09-07 07:35 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createIndex('CONTRACT_CONTRACT_ID', '{{%contracts}}', 'contractId');
Убрал

2021-09-07 07:36 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Зачем генерировать дополнительный мапинг и усложнять код?

2021-09-07 07:36 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'id' => $this->primaryKey()->unique(),
убрал. в инспекторе показывало что ключ не уникальный. убрал

2021-09-07 07:40 UTC, s1lver commented
С компонентом я все равно не согласен. Поообщался также с Женей.
- старые миграции пусть будут
- метод checkIndexName должен только проверять а не менять
- если проверка не проходит предлагать замену
- если согласны на змену менять

2021-09-07 07:41 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
Проверил, воспроизводится. Значит, у нас проблема: в console.php прописан шаблон
```php
'controllerMap' => [
	'migrate' => [
		'class' => MigrateController::class,
		'templateFile' => '@app/migrations/template/default_migration_template.php',
		...
	],
]
`

но он игнорируется.

2021-09-07 07:47 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Сделай snake_case, чтобы было однотипно с существующими объявлениями.
Заведи тикет с описанием проблемы - мол, snake_case в именах полей плохо потому-то и потому-то (идеально, если будут ссылки на какие-то стандарты), нужно подумать над рефакторингом в lowerCamelCase, получим такую-то выгоду.
И на ближайшем рефакторинге пройдёмся по всему коду, если решим, что это выгодно.

2021-09-07 07:48 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'id' => $this->primaryKey()->unique(),
А что за правило? Я такого не припомню в инспекциях.

2021-09-07 07:56 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'id' => $this->primaryKey()->unique(),
Возможно только у меня было. В DB Grid не показывало, при этом у всех других показывало уникальность. Сейчас не подтверждаю такое поведение

2021-09-07 07:58 UTC, pozitronik commented
> 
> 
> С компонентом я все равно не согласен. Поообщался также с Женей.
> 
>     * старые миграции пусть будут
> 
>     * метод checkIndexName должен только проверять а не менять
> 
>     * если проверка не проходит предлагать замену
> 
>     * если согласны на змену менять

Нет. Предоставление выбора ведёт к потенциальной разнице в создаваемых структурах, и нарушает сам принцип работы с миграциями.

Я не присутствовал при общении, не имел возможности привести свои аргументы, и хотя бы поэтому не могу принять его во внимание.

2021-09-07 07:59 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'id' => $this->primaryKey()->unique(),
Ну чёрт с ним. Увидишь ещё раз - маякни, интересно.

2021-09-07 08:13 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'contractId' => $this->integer()->notNull()->comment('ИД договора'),
Не надо придерживаться всегда и везде однотипности в именах полей. Надо использовать в зависимости от ситуации. Если входные данные мы получаем и обрабатываем внутри себя, ничего плохого в **snake_case** нет, тут у меня никаких противоречии. Но, если мы получаем данные из вне и они в **lowerCamelCase**, то нам нужно будет совершать дополнительные действия по мапингу, вместо того чтобы переложить работу на framework.

Т.е у меня на вход поле **testExample**, внутри у меня поле, согласно принятому неймингу, **test_example**.
Я хочу использовать AR. Иду переопределять, например, метод load() и потом занимаюсь поддержкой всего этого.

Или, у меня на входе поле **testExample**, внутри у меня поле **testExample**. Тогда я просто делаю load(), а дальше framework уже запускает проверки и делает сохранение. 

Плюс этого подхода в том, что ни нам не надо подстраиваться под данные интеграции, ни поставщику не надо подстраиваться под нас.

2021-09-07 08:48 UTC, s1lver commented on migrations/m210902_112037_create_contracts_table.php
> +			'status' => $this->json(),
Ну вот, уточнили. Эта инфа остается просто для информации и быстрого доступа. Подробнее уже Ваня достанет и сохранит связью

2021-09-07 09:00 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +		$this->createTable('{{%contracts}}', [
https://github.com/cusodede/dpl/pull/243

2021-09-07 09:41 UTC, pozitronik commented on migrations/m210902_112037_create_contracts_table.php
> +			'status' => $this->json(),
Обсудим голосом, это отдельный кейс, не блокирующий задачу.

2021-09-07 09:41 UTC, pozitronik approved these changes

2021-09-07 10:33 UTC, merged