Реализация методов вывода бонусов (паспортные данные)
cusodede/dpl pull request #259
Opened 2021-09-10 07:09 UTC by s1lver

- Добавлена возможность загрузки вариантов сканов паспорта для продавца
- Обновлена схема Swagger
- Добавлен вывод информации о паспортных данных в схему GraphQL

2021-09-10 09:23 UTC, pepebotika69 commented on modules/api/swagger/schema.yml
> +                - sellerId
А зачем sellerId required? я так понял, что этот метод для фронта. После авторизации, мы уже будем знать user. Или я что-то не понял?

2021-09-10 09:23 UTC, pepebotika69 commented on modules/graphql/schema/types/sellers/SellerType.php
> +					'type' => Type::int(),
series и number  у нас строка. Мы не знаем особености других паспортов. МБ в Гонгдурасе серия и номер такие: XXX 666YYT

2021-09-10 11:55 UTC, s1lver commented on modules/graphql/schema/types/sellers/SellerType.php
> +					'type' => Type::int(),
В Гондурасе?)

2021-09-12 18:30 UTC, pozitronik requested changes

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +		/** @noinspection NotOptimalIfConditionsInspection */
Если глушишь - дописывай коммент, почему инспекция ложно-положительная, либо почему её можно игнорировать, либо оставляй todo на исправление. Если не знаешь, как поступить, исходи из предположения, что сработало корректно.

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +	public function validateValue($value):?array {
Не нарушай инкапсуляцию.

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +		if (($validation = $this->validateValue($model->{$attribute})) !== null) {
Здесь и далее: yoda style мы юзаем, показано было настроить как.

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +		if (strlen($inn) === 11 || strlen($inn) === 9) {
```suggestion
		$inn = match (strlen($inn)) {
			9, 11 => '0'.$inn,
			default => $inn
		};
```

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +		//ИНН юрлиц
```suggestion
		return match(strlen($inn)) {
			10 => $this->validateLegal($inn),
			12 => $this->validatePerson($inn),
			default => [$this->message, []]
		};
```

2021-09-12 18:30 UTC, pozitronik commented on components/validators/InnValidator.php
> +		return <<<JS
Мы не используем инлайновые вставки. Вынести код в js, js подключать в ассете.

2021-09-13 09:05 UTC, s1lver commented on components/validators/InnValidator.php
> +		return <<<JS
Ага, ок. Так даже будет лучше

2021-09-14 18:48 UTC, pozitronik approved these changes

2021-09-16 14:14 UTC, pepebotika69 approved these changes

2021-09-17 10:30 UTC, merged