(#262) Добавлено правило для страницы обновления пароля
cusodede/dpl pull request #264
Opened 2021-09-10 11:47 UTC by s1lver

2021-09-10 11:59 UTC, pozitronik requested changes
Это не в конфиге надо менять, а в редиректе подставлять сразу корректный url `static::to('update-passord')`
С прочими правилами (register, login. etc) сделать аналогично.

2021-09-15 13:17 UTC, pozitronik commented
@s1lver up

2021-09-17 09:18 UTC, pozitronik approved these changes

2021-09-21 10:03 UTC, artemvolt approved these changes

2021-09-21 10:33 UTC, pepebotika69 approved these changes

2021-09-21 11:34 UTC, merged