Dspl 158
cusodede/dpl pull request #303
Opened 2021-09-24 18:53 UTC by pepebotika69

Тут сделан:
- модуль импорта, который работает на тасках
- загрузка правил в модель reward_models
- переписан интерфейс для дилера в связи с изменениями в его структуре
-добавлена либы для работы с сохранением много instances одной модели

Обязательно дерните миграции.

2021-09-27 11:40 UTC, pozitronik requested changes

2021-09-27 11:40 UTC, pozitronik commented on controllers/DealersController.php
> +		$modelsDealerContracts = [new DealerContracts()];
Эта инициализация может быть не обязательной, логично засунуть её в ветку else.

2021-09-27 11:40 UTC, pozitronik commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName())
Не могу благословить такую манипуляцию с массивом. Уж лучше получать formName из создаваемого экземпляра класса.

2021-09-27 11:40 UTC, pozitronik commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName()),
а здесь у тебя уже есть $modelsDealerContracts и formName можно взять из него.

2021-09-27 11:40 UTC, pozitronik commented on controllers/RewardsRulesStepsController.php
> +						$model = RewardsRules::find()->where(['soc' => $row[5]])
Жестоко.

2021-09-27 11:40 UTC, pozitronik commented on models/branches/active_record/references/RefBranches.php
> +			'code' => 'Код фиала',
Фиал - это такая чаша ритуальная. В неё, например, можно налить кровяку. А у нас - филиал, в него кровяку налить нельзя.

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/active_record/DealerChannelsAR.php
> + * @property int $deleted
Щелбан.
bool в определении и в валидаторе, плз.

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/active_record/DealerBranchesAR.php
> +			[['region', 'branch', 'deleted'], 'integer']
deleted bool

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/active_record/DealerRegionsAR.php
> +			[['dealer', 'region', 'deleted'], 'integer']
deleted bool

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/DealerContracts.php
> +		if (!empty($multipleModels)) {
[] !==

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/DealerContracts.php
> +		if (is_array($post)) {
Если $post не array, то у тебя функция не вызовется.
При этом, кстати, $post может быть объектом интерфейса Traversable и спокойно итерироваться в foreach()

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/DealerContracts.php
> +				if (!empty($item['id']) && isset($multipleModels[$item['id']])) {
не годится, работаем с массивами через методы хелпера с проверкой.

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/Dealers.php
> +	 * @param array $modelsDealerContracts
Где типизация массивов?

2021-09-27 11:40 UTC, pozitronik commented on models/dealers/Dealers.php
> +		try {
Это выглядит очень неаккуратно, будем переделывать вместе.

2021-09-27 11:40 UTC, pozitronik commented on modules/import_common/ImportCommonModule.php
> +class ImportCommonModule extends Module {
Хорошо бы доку описать, что вообще за херня тут творится.

2021-09-27 11:40 UTC, pozitronik commented on modules/import_common/helpers/Helper.php
> +class Helper {
Ну хелпер и хелпер, да?

2021-09-27 11:40 UTC, pozitronik commented on modules/import_common/models/jobs/branches/CreateBranchesJob.php
> +	public function execute($queue) {
По чесноку, джобы даже смотреть не буду. Импорт такое дело, что слишком формальные требования на него не натягиваются. Если работает - то и ок.

2021-09-27 11:40 UTC, pozitronik commented on modules/status/models/traits/StatusesTrait.php
> +			$user = Yii::$app->request->isConsoleRequest
Я не очень понимаю, что здесь происходит, но этот код меня немного напрягает. Обсудим голосом.

2021-09-27 11:40 UTC, pozitronik commented on modules/status/models/Status.php
> +		if (!Yii::$app->request->isConsoleRequest){
неправильная комбинация условий.

2021-09-27 12:42 UTC, pepebotika69 commented on controllers/DealersController.php
> +		$modelsDealerContracts = [new DealerContracts()];
оня обязательная, смотри строчку:
$dataForView = compact('model', 'modelsDealerContracts')

2021-09-27 12:43 UTC, pepebotika69 commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName())
так?
			$modelsDealerContracts = DealerContracts::createMultiple(
				Yii::$app->request->post((new DealerContracts())->formName())
			);

2021-09-27 12:46 UTC, pepebotika69 commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName()),
не понял

2021-09-27 12:47 UTC, pozitronik commented on controllers/DealersController.php
> +		$modelsDealerContracts = [new DealerContracts()];
Если выполняется `Yii::$app->request->isPost`, то `$modelsDealerContracts` переопределяется, значит инициализация была лишней. Её надо сдвинуть в ветку else.

2021-09-27 12:49 UTC, pepebotika69 commented on controllers/RewardsRulesStepsController.php
> +						$model = RewardsRules::find()->where(['soc' => $row[5]])
не понял

2021-09-27 12:50 UTC, pepebotika69 commented on models/branches/active_record/references/RefBranches.php
> +			'code' => 'Код фиала',
DONE)

2021-09-27 12:50 UTC, pozitronik commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName())
Как вариант. Не очень хороший, да.
Либо добавить проверку а-ля
```php
...
$formName = ArrayHelper::getValue($modelsDealerContracts, '0', new Exception(...))->formName();
...
```
что тоже не особо ок, и тут надо что-то другое придумать.

2021-09-27 12:51 UTC, pozitronik commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName()),
Да, я ошибся.

2021-09-27 12:54 UTC, pozitronik commented on controllers/RewardsRulesStepsController.php
> +						$model = RewardsRules::find()->where(['soc' => $row[5]])
У нас тут контроллер.
Мы в этот контроллер пихаем какой-то конфиг. Это не самая лучшая идея, конечно, но что поделать, если этот конфиг непосредственно влияет на некоторый Action этого контроллера. Как бы можно перетерпеть.
Но потом в этом конфиге появляются замыкания, а в замыканиях - уже прямо и выборки какие-то.
Это жестоко и грустно, и даже немножечко подло: мы-то хотели как лучше, а получилось, что шлём MVC лесом.

2021-09-27 13:22 UTC, pepebotika69 commented on modules/import_common/ImportCommonModule.php
> +class ImportCommonModule extends Module {
DONE

2021-09-27 13:34 UTC, pepebotika69 commented on modules/import_common/helpers/Helper.php
> +class Helper {
DONE

2021-09-27 13:36 UTC, pepebotika69 commented on modules/status/models/traits/StatusesTrait.php
> +			$user = Yii::$app->request->isConsoleRequest
Дело в том что модуль status сделан только для работы с web, если через консоль то юзера не найдет.

2021-09-27 13:37 UTC, pepebotika69 commented on modules/status/models/Status.php
> +		if (!Yii::$app->request->isConsoleRequest){
как ты предлагаешь?

2021-09-27 13:45 UTC, pepebotika69 commented on controllers/RewardsRulesStepsController.php
> +						$model = RewardsRules::find()->where(['soc' => $row[5]])
Я тебя понял. Я посмотрел как у тебя сделано в DealersController. Да, у тебя там не замыкания, но я так понял, что надо делать так. Могу вынести все это в модель RewardsRulesSteps и создать тас статический класс который буду вызывает в контроллере. как вариант

2021-09-27 13:56 UTC, pepebotika69 commented on controllers/DealersController.php
> +				Yii::$app->request->post($modelsDealerContracts[0]->formName())
не очень понял что улучшилось, но вот a4091617

2021-09-27 16:13 UTC, pozitronik approved these changes

2021-09-28 07:48 UTC, s1lver commented
Если добавлять без кода, то появляется сообщение "Ошибка"
<img width="1284" alt="Снимок экрана 2021-09-28 в 10 43 04" src="https://user-images.githubusercontent.com/4567634/135045540-f693c3e8-b7e9-45d1-af9b-d763de3473b7.png">

2021-09-28 07:49 UTC, s1lver requested changes

2021-09-28 07:49 UTC, s1lver commented on modules/status/models/Status.php
> +		 */
После этого изменения забыли убрать больше не используемый импорт ```modules/status/models/Status.php```

2021-09-28 08:08 UTC, pepebotika69 commented on modules/status/models/Status.php
> +		 */
DONE

2021-09-28 08:09 UTC, pepebotika69 commented
> Если добавлять без кода, то появляется сообщение "Ошибка"
> <img alt="Снимок экрана 2021-09-28 в 10 43 04" width="1284" src="https://user-images.githubusercontent.com/4567634/135045540-f693c3e8-b7e9-45d1-af9b-d763de3473b7.png">

Готово. Забыл rules обновить

2021-09-28 10:23 UTC, s1lver commented
Кнопку загрузки правил надо добавить в интерфейс, раз уже для нее контроллер

2021-09-28 10:25 UTC, s1lver commented
Шаблон для начисления правил надо складировать в наш Confluence

2021-09-28 10:27 UTC, pozitronik commented
> 
> 
> Кнопку загрузки правил надо добавить в интерфейс, раз уж есть для нее контроллер

У нас в каждом контроллере-наследнике DefaultController есть скрытый экшен import. Отдельную кнопочку, конечно, прорисовать несложно, но предполагается, что импорт - чисто утилитарная штука, недоступная в боевом режиме никому, кроме разработчиков.

2021-09-28 10:39 UTC, s1lver commented
Тогда нарисовать с условием видимости = Администратор, Разработчик, Тестировщик. Или если DEV. 
Надо дать тестировщикам это тестить, да и самим полезно

2021-09-28 10:41 UTC, pozitronik commented
> 
> 
> Тогда нарисовать с условием видимости = Администратор, Разработчик, Тестировщик. Или если DEV. Надо дать тестировщикам это тестить, да и самим полезно

Это делается автоматически, по наличию прав доступа.
Я о том толкую, что для текущей задачи это можно не делать, отложить в новую задачу.

2021-09-28 11:33 UTC, s1lver commented
Ясно-понятно

2021-09-28 11:33 UTC, s1lver approved these changes

2021-09-28 11:34 UTC, merged