DMP. Остальные валидаторы
cusodede/dpl pull request #309
Opened 2021-09-27 13:52 UTC by artemvolt

2021-09-27 16:58 UTC, pozitronik requested changes

2021-09-27 16:58 UTC, pozitronik commented on models/rewards_validators/validators/orders/simcard/HasActivityOnSimcardValidator.php
> +			if (0 == $callsDuration && $fee > 0) {
Здесь точно `==`?

2021-09-27 16:58 UTC, pozitronik commented on modules/dmp/models/biis_fct/active_record/FctUsagePrepChaNAr.php
> -class FctUsagePrepChaNAr extends DmpBaseActiveRecord {
После того, как ты изменил наследование, у тебя из иерархии пропал класс `BaseActiveRecord` и метода `static::find()` больше нет (в `getSumDurationCall()` он вызывается).

2021-09-27 16:58 UTC, pozitronik commented on models/rewards_validators/validators/orders/simcard/HasIncomingCalls.php
> +			if ($sumMinutesCallsDuration < 30) {
Магические цифры либо описываем константами, либо выносим в параметры с этими такими значениями.

2021-09-27 16:58 UTC, pozitronik commented on models/rewards_validators/validators/orders/simcard/HasOutGoingCalls.php
> +			if ($sumMinutesCallsDuration < 30) {
Магические цифры либо описываем константами, либо выносим в параметры с этими такими значениями.

2021-09-28 07:54 UTC, s1lver commented on models/rewards_validators/validators/orders/simcard/HasOutGoingCalls.php
> +			if ($sumMinutesCallsDuration < 30) {
Говорили же что эти параметры будут из настроек тянутся)

2021-09-28 08:28 UTC, pozitronik commented on models/rewards_validators/validators/orders/simcard/HasOutGoingCalls.php
> +			if ($sumMinutesCallsDuration < 30) {
> 
> 
> Говорили же что эти параметры будут из настроек тянутся)

Настройки реализованы. Значит, или туда, или в константы.

2021-09-28 10:23 UTC, artemvolt commented
Поправил

2021-09-28 19:09 UTC, pozitronik approved these changes

2021-09-28 19:09 UTC, merged