(#326) Изменение архитектуры контрактов
cusodede/dpl pull request #330
Opened 2021-10-01 07:42 UTC by s1lver

2021-10-01 10:14 UTC, pepebotika69 commented on modules/nsis/models/job/DolContractRegisterCompleteJob.php
> -				&& self::insertConnections(self::createInsertRows($responseParser, $this->modelContracts))) {
тут не очень понял зачем менять.

2021-10-01 10:58 UTC, s1lver commented on migrations/m210930_134816_create_contracts_events_table.php
> +		$this->dropColumn('contracts', 'status');
Потому что мы меняем архитектуру) В текущей реализации сущность contracts не должна содержать эти поля

2021-10-04 09:26 UTC, pozitronik commented
PR в драфте.

2021-10-04 12:50 UTC, pozitronik requested changes

2021-10-04 12:50 UTC, pozitronik commented on models/contracts/Contracts.php
> +					);
Не трожь форматирование.

2021-10-04 12:50 UTC, pozitronik commented on views/contracts/index.php
> +					),
Не трожь форматирование.

2021-10-04 14:01 UTC, s1lver commented on models/contracts/Contracts.php
> +					);
Что за страсть такая скролить по горизонтали)

2021-10-04 17:22 UTC, pozitronik commented on models/contracts/Contracts.php
> +					);
У тебя когда день рождения? Мы с пацанами тебе на нормальный монитор скинемся.

2021-10-05 08:08 UTC, pepebotika69 commented on models/contracts/Contracts.php
> +					);
давайте мне тоже)

2021-10-05 08:15 UTC, pozitronik commented on models/contracts/Contracts.php
> +					);
> давайте мне тоже)

Ок, сначала ты скидываешься Женьке, потом Женька скидывается тебе.

Если серьёзно - можем договориться о максимальных размерах строк кода, настроить линтер, и жить так.

Ну или можете soft wrap включить ещё.

2021-10-05 09:48 UTC, pepebotika69 approved these changes

2021-10-05 09:48 UTC, pepebotika69 commented on models/contracts/Contracts.php
> +					);
"Если серьёзно - можем договориться о максимальных размерах строк кода, настроить линтер, и жить так."
Давай

2021-10-05 10:12 UTC, s1lver commented on models/contracts/Contracts.php
> +					);
В SonarLint это - правило php:S103

2021-10-05 10:15 UTC, pozitronik commented on models/contracts/Contracts.php
> +					);
> 
> 
> В SonarLint это - php:S103

У нас не SonarLint, у нас IDE поддерживает EditorConfig, вот туда и  добавим.

Впрочем, это всё предмет отдельного обсуждения. Сейчас - форматирование вернуть.

2021-10-05 10:34 UTC, s1lver commented
Обнаружена бага

2021-10-05 10:55 UTC, s1lver commented on models/contracts/Contracts.php
> +					);
Ты и так его вернул

2021-10-05 10:56 UTC, s1lver commented
Теперь нормально

2021-10-05 11:29 UTC, pozitronik approved these changes

2021-10-05 11:29 UTC, merged