Dspl 161
cusodede/dpl pull request #331
Opened 2021-10-01 08:33 UTC by pepebotika69

Интеграция с ДОЛ ФИАС.
Тестить можено через ВПН
(http://fias.beelinetst.ru/swagger/index.html)

2021-10-02 09:11 UTC, pozitronik requested changes
+комментарию - не забывай использовать конструкцию сравнения присвоения.

2021-10-02 09:11 UTC, pozitronik commented on modules/dol/models/fias/DolApiFiasInterface.php
> +	public function requestSuggestedEntities(string $url, string $text, array $options = [], string $parserClass = ResponseSuggestedParser::class):array;
Типизировать `$parserClass` как `string` не совсем правильно. Да, имя класса у нас содержится в строке, но в функцию нельзя передать _любую_ строку.
Что можно сделать:
1. Для класса `ResponseSuggestedParser` придумать какой-то интерфейс, пусть даже чисто номинальный.
2. Типизировать параметр `$parserClass` этим интерфейсом.

Что сразу получим - конструкция 
```php
(new $parserClass($content))
```

будет явно представлять модель с этим интерфейсом, и мы не будем спотыкаться, смотря на её свойства.

2021-10-03 12:10 UTC, pepebotika69 commented
> +комментарию - не забывай использовать конструкцию сравнения присвоения.

Это обязательно? Если да, то буду использовать, если нет, то мне понятнее без нее.

2021-10-03 12:25 UTC, pepebotika69 commented on modules/dol/models/fias/DolApiFiasInterface.php
> +	public function requestSuggestedEntities(string $url, string $text, array $options = [], string $parserClass = ResponseSuggestedParser::class):array;
Не получится. Если тип будет интерфейс, то передавать в метод нужно объект. Если передавать объект, то это (new $parserClass($content)) уже не прокатит. И к тому же, BaseHandler::handleWithErrors($response) может выкинуть исключение: зачем создавать объект заранее, если может до него дело и не дойдет?

2021-10-03 14:36 UTC, pozitronik commented
> 
> 
> > +комментарию - не забывай использовать конструкцию сравнения присвоения.
> 
> Это обязательно? Если да, то буду использовать, если нет, то мне понятнее без нее.

В случаях, если это позволяет избежать создания новой переменной, нужной только внутри условия - да, обязательно.
В других случаях - желательно, но докапываться не буду.

2021-10-03 15:09 UTC, pozitronik commented on modules/dol/models/fias/DolApiFiasInterface.php
> +	public function requestSuggestedEntities(string $url, string $text, array $options = [], string $parserClass = ResponseSuggestedParser::class):array;
Ну да, прямо так не получится, но если сказать «ахалай-махалай» и немножко дунуть, то вполне: 8a1ec88

2021-10-03 18:14 UTC, pepebotika69 commented on modules/dol/models/fias/DolApiFiasInterface.php
> +	public function requestSuggestedEntities(string $url, string $text, array $options = [], string $parserClass = ResponseSuggestedParser::class):array;
ну... я понял, но как то сложно стало и запутано, нет?

2021-10-03 18:15 UTC, pepebotika69 commented
> > > +комментарию - не забывай использовать конструкцию сравнения присвоения.
> > 
> > 
> > Это обязательно? Если да, то буду использовать, если нет, то мне понятнее без нее.
> 
> В случаях, если это позволяет избежать создания новой переменной, нужной только внутри условия - да, обязательно. В других случаях - желательно, но докапываться не буду.

ясно

2021-10-03 18:17 UTC, pozitronik commented on modules/dol/models/fias/DolApiFiasInterface.php
> +	public function requestSuggestedEntities(string $url, string $text, array $options = [], string $parserClass = ResponseSuggestedParser::class):array;
А передавать имя класса в метод другого класса, инициализируя первый класс результатом работы другого метода второго класса - не сложно?

2021-10-03 18:21 UTC, pozitronik approved these changes

2021-10-04 11:12 UTC, s1lver approved these changes

2021-10-04 11:13 UTC, merged