Issue 329
cusodede/dpl pull request #332
Opened 2021-10-01 11:42 UTC by pozitronik

Теперь договора без контактов продавца могут легитимно получать вознаграждения. Они рассчитываются, но никому не выплачиваются, просто висят в привязке к контракту.

2021-10-04 11:38 UTC, s1lver requested changes

2021-10-04 11:38 UTC, s1lver commented on models/contracts/Contracts.php
> +		if (!$this->isFinalStatus || null === $this->login_register) return null;
isFinalStatus больше тут не нужен. Надо проверить задачку 326 и тогда это можно убрать

2021-10-04 11:38 UTC, s1lver commented on models/contracts/Contracts.php
> +		return $this->isFinalStatus && $this->hasSOC && [] === $this->relatedRewards;
И тут

2021-10-04 11:38 UTC, s1lver commented on models/seller/interfaces/SellerInterface.php
> +
Это интерфейс заглушка или забыт код?

2021-10-04 12:04 UTC, pozitronik commented on models/contracts/Contracts.php
> +		if (!$this->isFinalStatus || null === $this->login_register) return null;
Изменение опирается на стабильный код, требовать от него учёта будущих изменений нельзя.
Т.е. как замечание - мол, будет так-то и так-то, - принимается, но и всё на этом.

2021-10-04 12:13 UTC, pozitronik commented on models/seller/interfaces/SellerInterface.php
> +
Ни то, ни другое.
Этим интерфейсом маркируются объекты одинаковой структуры, но разного назначения.
При регистрации вознаграждений в `\app\models\contracts\Contracts::registerRewards()` мы должны передать объект продавца, чтобы по его связям найти подходящее правило. Эти связи могут появиться только после сохранения объекта продавца в БД, что нам не всегда нужно.
Поэтому мы создаём "виртуального продавца" - объект с нужными полями, но не имеющий отражения на БД. И "реальный" и "виртуальный" продавцы наследуют этот интерфейс, а принимающая функция проверяет принадлежность.

Таким образом мы защищаемся от "левых" параметров и не теряем типизацию.

2021-10-05 07:19 UTC, s1lver approved these changes
Понятно

2021-10-05 07:21 UTC, merged