fix_in_tests - Modify test after Dealer structure modification
cusodede/dpl pull request #346
Opened 2021-10-04 13:00 UTC by pepebotika69

Поправил DealersCest

2021-10-04 13:18 UTC, artemvolt requested changes

2021-10-04 13:18 UTC, artemvolt commented on models/tests/store/active_record/references/RefSellingChannelsTest.php
> +		$self->save();
save мы дергаем уже в тестах. 
createTestRecord возвращает ток объект текущего класса без сохранения

2021-10-04 13:18 UTC, artemvolt commented on models/tests/store/active_record/references/RefSellingChannelsTest.php
> +		$self->save();
Так же надо докинуть трейт
use app\models\tests\core\prototypes\ActiveRecordTraitTest;
чтобы можно было дергать метод  saveAndReturn()

2021-10-04 14:06 UTC, pepebotika69 commented on models/tests/store/active_record/references/RefSellingChannelsTest.php
> +		$self->save();
готово

2021-10-04 18:56 UTC, pozitronik commented
Я из проверки самоустраняюсь, т.к. слабо понимаю, что там происходит.

2021-10-05 07:08 UTC, s1lver commented
Давайте уже не усложнять себе жизнь добавляя все новое в это пространство.

2021-10-05 07:14 UTC, s1lver requested changes

2021-10-05 07:14 UTC, s1lver commented on tests/functional/controller/DealersCest.php
> +		$region = RefRegionsBeeTest::createTestRecord()->saveAndReturn();
```php
$region = (new RefSellingChannels([
			'name' => 'Франшиза'
		]))->->saveAndReturn();
```
Чем эта запись хуже? На мой взгляд происходит одно и тоже. При этом есть наследование которое уже включает ```use ActiveRecordTraitTest;```

2021-10-05 07:17 UTC, s1lver commented on tests/functional/controller/DealersCest.php
> +		$region = RefRegionsBeeTest::createTestRecord()->saveAndReturn();
аааа...там еще и трайт для тестов(

2021-10-05 09:51 UTC, pepebotika69 commented
> Давайте уже не усложнять себе жизнь добавляя все новое в это пространство.

как понять все новое?

2021-10-05 09:59 UTC, pepebotika69 commented on tests/functional/controller/DealersCest.php
> +		$region = RefRegionsBeeTest::createTestRecord()->saveAndReturn();
можно и так, но когда у тебя будут куча таких будет неудобно читать. ЕСли дело в том что reference дублируется в справочниках, то надо это глобально чинить

2021-10-05 10:58 UTC, s1lver commented on tests/functional/controller/DealersCest.php
> +		$region = RefRegionsBeeTest::createTestRecord()->saveAndReturn();
> ЕСли дело в том что reference дублируется в справочниках, то надо это глобально чинить

Это вторая беда

2021-10-05 11:06 UTC, s1lver commented
> > Давайте уже не усложнять себе жизнь добавляя все новое в это пространство.
> 
> как понять все новое?

Я имею ввиду вот что: появляется какой-то странный код, который, в какой-то момент, решают оставить!!! Потом, по аналогии, начинают туда добавлять новый и новый код. Но, в других местах такое не проходит или проходит. И начинается разброд и шатание.

Думаю что раз все равно "пишем тесты" и никто "не торопит", то можно новое не добавлять. Я не так чтобы много пишу тесты поэтому, мне не принципиален этот момент. Однако, ещё раз, хочу его подсветить.

2021-10-05 11:24 UTC, artemvolt commented on tests/functional/controller/DealersCest.php
> +		$region = RefRegionsBeeTest::createTestRecord()->saveAndReturn();
> аааа...там еще и трайт для тестов(

Как я и говорил раньше, Паша не пропускал мои правки в основных моделях,  поэтому все живет в наследованных моделях.
Хочешь поменять? Давай вынесем еще раз на обсуждение, но сейчас в общем потоке это мы должны пропустить.

2021-10-05 11:30 UTC, artemvolt commented
> > > Давайте уже не усложнять себе жизнь добавляя все новое в это пространство.
> > 
> > 
> > как понять все новое?
> 
> Я имею ввиду вот что: появляется какой-то странный код, который, в какой-то момент, решают оставить!!! Потом, по аналогии, начинают туда добавлять новый и новый код. Но, в других местах такое не проходит или проходит. И начинается разброд и шатание.
> 
> Думаю что раз все равно "пишем тесты" и никто "не торопит", то можно новое не добавлять. Я не так чтобы много пишу тесты поэтому, мне не принципиален этот момент. Однако, ещё раз, хочу его подсветить.

Не проходит в общем проекте, тестами заправлял только я.

2021-10-05 11:30 UTC, artemvolt approved these changes

2021-10-05 12:06 UTC, s1lver approved these changes

2021-10-05 12:17 UTC, merged