Avolt issues 35 codeception
cusodede/dpl pull request #36
Opened 2021-06-01 05:54 UTC by artemvolt

2021-06-01 06:12 UTC, artemvolt commented on codeception.yml
> +      dump: 'tests/_data/dumps/base_structure.sql'
Предполагается, что у нас будет делаться дамп голой структуры бд без данных - это проще, удобнее и быстрее, чем накатывать миграции на тестовую бд.
Далее, перед запуском тестов, убиваются все таблицы тестовой бд и накатывается дамп, дальше уже выполняются тесты.
Каждый тест (это метод) может записывать данные, эти данные живут только в этом тесте и удаляются, как только он завершится (через транзакции очистка происходит).

2021-06-01 06:15 UTC, artemvolt commented on codeception.yml
> +      dump: 'tests/_data/dumps/base_structure.sql'
Если у нас будут появляться справочники, которые нужны везде, например, типы сим-карт, адреса офисов билайн и т.д. По ним будет создавать отдельные дампы и укажем в конфете codeception.

2021-06-02 18:03 UTC, artemvolt commented on README.MD
> +1) Создаем тестовую базу данных, пустую.
надо будет запустить, после того как выкатят другую мою ветку, в которой основной код.

2021-06-02 18:04 UTC, artemvolt commented on tests/acceptance.suite.yml
> +modules:
пока забиваем, приемочные потом.

2021-06-03 07:57 UTC, pozitronik requested changes
В инструкции непонятки.
>сomposer install --dev

Если пакеты уже стоят (кроме кодесепшена), то нужен composer update

>vendor/bin/codeception run

При этом имя стартового скрипта - **codecept**

---
Оно, в итоге, не стартует:
```
> codecept run


In Configuration.php line 164:
                                              
  Configuration file could not be found.      
  Run `bootstrap` to initialize Codeception.  
```

2021-06-03 20:44 UTC, artemvolt commented
Поправил readme. После запуска правда залетят файлы ассетов в папку assets, а не web/assets.
С этим разберусь.

2021-06-06 11:10 UTC, pozitronik approved these changes

2021-06-06 11:10 UTC, closed without merging

2021-06-06 11:12 UTC, pozitronik commented
Код принят, это готовое решение по включению тестов. Но мержить в master пока не будем, нет нужды. Пусть лежит, готовое для подключения в любой момент.