Issue 31
cusodede/dpl pull request #37
Opened 2021-06-01 10:01 UTC by pepebotika69

See: #31

2021-06-01 11:50 UTC, pozitronik requested changes
По комментам

2021-06-03 18:37 UTC, pozitronik commented on controllers/UploadsController.php
> -	 * Отдаёт загруженные файлы по ID
Мы не должны работать с FileStorage напрямую. Это хранилище, к которому мы должны обращаться только по ключам [модель|атрибут].
Разберём голосом.

2021-06-03 18:38 UTC, pozitronik commented on controllers/UploadsController.php
> +	public function actionDownload(?int $id = null):void {
Этот контроллер вообще не нужен, короч.

2021-06-03 18:48 UTC, pozitronik commented on models/sys/users/active_record/Users.php
> + * @property Sellers $relatedSeller Связь с продавцом
Вот тут приходится подумать.
Users - это глобальная проектная сущность, т.е. она попадёт в ppl, где такой связи нет.
От этого думаем: а нужна ли нам вообще такая связь? Ведь любой продавец имеет аккаунт, но не каждый аккаунт принадлежит продавцу.
И если начинаем пилить какие-то системные разграничения по правам, типа саппорт может редачить продавцов, но не может делать продавцов из пользователей, а админ наоборот; нам приходится начинать это учитывать в интерфейсах, в коде, в аллахе, мы сходим с ума и три раза стреляем себе в голову.

Убирай связь, и из вьюх пользователя тоже убирай. Если прям надо будет сделать редактор "превратить пользователя в продавца", для этого сделаем отдельный экшен от продавцов.

2021-06-03 18:49 UTC, pozitronik commented on models/sys/users/Users.php
> +	public static function getDefaultPassword():string {
Это зачем?

2021-06-03 18:51 UTC, pozitronik commented on controllers/SellersController.php
> +			$model->uploadDocs($_FILES);
Не продумана загрузка файлов, завтра проговорим.

2021-06-03 18:53 UTC, pozitronik commented on models/seller/Sellers.php
> +	public function uploadDocs(array $files):void {
Не продумано, и не по канону.

2021-06-04 07:49 UTC, pepebotika69 commented on models/sys/users/active_record/Users.php
> + * @property Sellers $relatedSeller Связь с продавцом
Согласен. Исправил. Запушил.

2021-06-04 07:52 UTC, pepebotika69 commented on models/sys/users/Users.php
> +	public static function getDefaultPassword():string {
можно было константу сделать public. или у тебя другой подход?

2021-06-05 12:58 UTC, closed without merging