Issues #27 switch identity
cusodede/dpl pull request #39
Opened 2021-06-02 20:04 UTC by artemvolt

Первый линч

2021-06-02 20:05 UTC, artemvolt commented on models/sys/permissions/Permissions.php
> +    public static function loginAsAnotherUser()
можно сделать create и туда кидать параметры, пока так сделал,

2021-06-02 20:07 UTC, artemvolt commented on models/vendor/yii2/WebUser.php
> +<?php
Честно говоря, я бы не стал класть этот класс в модели, больше относится к каким-нибудь components.
Переключение профиля относится к компоненту веба, поэтому методы поместил сюда, расширил базовый класс.

2021-06-02 20:07 UTC, artemvolt commented on views/layouts/main.php
> +			<?php if (Yii::$app->session->hasFlash('error')) { ?>
вместо : использовал класические скобки. Без скобок не работает подсветка закрывающей.

2021-06-02 20:08 UTC, artemvolt commented on views/users/index.php
> +					'login-as-another-user' => static function (string $url, Users $model) {
пока не стал добавлять visible к кнопкам, пока предположил, что в раздел могут заходить только админы.

2021-06-03 06:39 UTC, Fullchaos approved these changes

2021-06-03 07:27 UTC, pozitronik requested changes
Не принимается.
1) Не использован проектный code style.
2) Не использована проектная инспекция.
3) В шаблонах нужно использовать только альтернативный синтаксис.
4) В задачу попали тесты. Всё понимаю, но пока это не требовалось - тесты мы ещё не ввели, они как бы за скобками. Убери пока, будем их вводить отдельно.

2021-06-03 11:36 UTC, alxlapin commented
> 3. В шаблонах нужно использовать только альтернативный синтаксис.

В чем преимущество такого подхода?

2021-06-03 20:43 UTC, artemvolt commented
Поправил замечания, но видимо надо будет еще обсудить.
Вроде инспекции подрубил и что-то поправил, но много старых инспекций из других участков кода, которые я не трогал.

2021-06-09 09:52 UTC, closed without merging