Issue: #442. Пакетная обработка фродовых правил. Базовая структура.
cusodede/dpl pull request #447
Opened 2021-10-21 08:41 UTC by artemvolt

После события из дола, если правило сработает, у нас создаются записи для фродовых проверок в таблице 
rewards_rules_validators_statuses

Добавил колонку - дата создания, чтобы отсчитывать кол-во дней с момента события.
Крон-команда ``` php yii fraud/check-already``` проверяет какие записи по каким валидаторам есть, если их достаточно и их время пришло, кидает джобу на каждый валидатор. 

Джоба по интерфейсу, передает коллекцию записей rewards_rules_validators_statuses конкретному валидатору, которые нужно проверить, валидатор меняет статусы у записей и возвращает обратно в джобу.
Джоба обновляет статусы в бд. 

Так как дмп у нас не умеет работать асинхронно, у нас джобы будут выполняться последовательно. Если будут две одинаковые джобы, то после работы первой, второй ничего не достанется и она просто протухнет.

Крутить фрод будем в какой-то отдельной очереди, не queue, чтобы не тормозить основной поток.

2021-10-21 11:19 UTC, pozitronik commented on models/rewards_bonuses/RewardsBonuses.php
> +		$status = BaseJobValidator::STATUS_NONE;
>потому что у них завязка на джобу (способ выполнения)

Не обязательно, есть интерфейс без джобы, синхронный.

2021-10-21 12:14 UTC, artemvolt commented on models/rewards_bonuses/RewardsBonuses.php
> +		$status = BaseJobValidator::STATUS_NONE;
Ну ок, тогда надо будет просто вынести на рефакторинг. Убрать лишнее

2021-10-31 19:56 UTC, pozitronik requested changes

2021-10-31 19:56 UTC, pozitronik commented on models/sys/users/active_record/Users.php
> +			}],
Точно, я в который раз на этом обсираюсь. Вот так хорошо:
```suggestion
			[['daddy'], 'default', 'value' => fn() => Yii::$app->user->id??null]
```

2021-11-01 07:26 UTC, pozitronik approved these changes

2021-11-01 07:32 UTC, merged