Issue 31
cusodede/dpl pull request #53
Opened 2021-06-23 14:16 UTC by pepebotika69

Доработка "Регистрация продавца"

2021-06-23 16:53 UTC, pozitronik requested changes

2021-06-23 16:53 UTC, pozitronik commented on models/addresses/Addresses.php
> +			implode(
🔥👁️👁️🔥 
Зачем раскукоживать?

2021-06-23 16:53 UTC, pozitronik commented on models/dealers/DealersSearch.php
> +		if ($user->hasPermission(['show_all_dealers'])) {
Мне не нравится, как сделана фильтрация. Это совершенно не то, о чём мы говорили по поводу #51

2021-06-24 06:26 UTC, pepebotika69 commented on models/addresses/Addresses.php
> +			implode(
не в одной строке же) ПО хорошему и это array_filter([$this->index, $this->refRegion->name, $this->region, $this->city, $this->street, $this->building]) нужно было раскукоживать

2021-06-26 08:36 UTC, pozitronik approved these changes

2021-06-26 08:36 UTC, merged