Issue #76. Регистрация продавца
cusodede/dpl pull request #88
Opened 2021-07-15 13:22 UTC by artemvolt

1. Фронт шлет смс в /api/seller/register, отправляет смс и возвращается токен
2. Фронт шлет запрос на подтверждение /api/seller/confirm-register c токеном.
Если смс протухла на этом этапе, запрашиваем на урле /api/seller/repeat-send-sms, смс вставляем снова в confirm-register. 
3. На этапе паспортных данных, если вдруг токен дола для регистрации тухнет.
Фронт отправляет запрос на /api/seller/repeat-send-sms, потом подтвержает запросом на /api/seller/repeat-confirm-sms и токен кидает в отправку с паспортом (паспорт пока в процессе реализации)

2021-07-17 12:06 UTC, pozitronik requested changes
Привёл код к ожидаемому виду (смотри по коммитам), смержил с master.
Осталось исправить два fixme + разобраться с `Users::getStoresViaRole()` которого вообще не должно быть. Но это можно отложить до первого большого рефакторинга.

2021-07-19 08:28 UTC, artemvolt commented
getStoresViaRoles() пока предлагаю оставить, пометить как TODO

2021-07-19 08:34 UTC, artemvolt commented
Предлагаю все же перестать считать примеры кода фреймворка как эталон или использовать их какие-то решения, как эталон, по крайней мере с гетерами и сетерами.
Нет ни гетеров ни сетеров , есть сущность, к который ты можешь задавать вопросы, но не выкручивать кишки снаружи. Меняем состояние только внутри объекта.
То есть, 
(new Users()->setConfirmedStatus(), ->isConfirmedStatus() ->isDeletedStatus(), setStatus(self::CONFIRMED)
а не ->getIsDeleted(), ->setIsDeleted() и ни в коем случае $users->status = Users::DELETED

2021-07-19 08:35 UTC, artemvolt commented
setStatus(self::CONFIRMED) - так как модели все же юзают базовый функционал фреймворка с магическими методами, то лучше писать changeStatus, чтобы не перебивать базовые функции.

2021-07-19 10:38 UTC, artemvolt commented on models/seller/Sellers.php
> +	 * fixme: вся логика с присвоением статусов должна выполняться в StatusesTrait
пока не знаю, как лучше сделать. Предлагаю пофиксить, как сделаем основную регу и авторизацию.

2021-07-19 19:11 UTC, pozitronik commented
> 
> 
> getStoresViaRoles() пока предлагаю оставить, пометить как TODO



> 
> 
> Предлагаю все же перестать считать примеры кода фреймворка как эталон или использовать их какие-то решения, как эталон, по крайней мере с гетерами и сетерами.
> Нет ни гетеров ни сетеров , есть сущность, к который ты можешь задавать вопросы, но не выкручивать кишки снаружи. Меняем состояние только внутри объекта.
> То есть,
> (new Users()->setConfirmedStatus(), ->isConfirmedStatus() ->isDeletedStatus(), setStatus(self::CONFIRMED)
> а не ->getIsDeleted(), ->setIsDeleted() и ни в коем случае $users->status = Users::DELETED
> 
> Таким подходом мы сохраняем инкапсуляцию и данными оперирует тот объект, который ими владеет.

Не могу согласиться про отказ от геттеров сеттеров. Мне видится, что сам подход к смене статусов спорный, реализация такая, что она _заставляет_ "задавать вопросы".
Статус **подтверждения** (не какой-то общий, а именно подтверждения) - это логическое значение, подтверждён номер, или нет. И логично бы было, выгляди оно "снаружи" именно как флаг:
```php
$model->confirmed = true;
if ($model->confirmed) {...}
```
Будь этот "флаг" реализован через логическую переменную (или атрибут БД, как флаг $deleted, например) - мы бы без всяких сомнений писали именно так ⬆️ . Не пишем же мы 
```php
if ($model->getIsDeleted()) {...};
```
мы просто обращаемся к свойству.

Свойство, реализуемое фреймворком через геттеры/сеттеры именно такое представление нам позволяет организовать. Инкапсуляция тут не нарушается - объект (атрибут `(int)$status`), хранящий состояние, всё ещё существует внутри модели, мы не меняем его напрямую, и вообще о нём ничего не знаем.
Появившееся свойство можно переименовать из isConfirmed в просто confirmed, это уберёт "вопрос про вопрос".

2021-07-19 19:14 UTC, pozitronik approved these changes

2021-07-19 19:14 UTC, merged